language: c

sudo: required
services: docker

script: ./travis_build.sh
after_failure: cat cctools.test.fail

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos6
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos7
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-ubuntu16.04
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-debian9.2
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-opensuse42.3
