language: c

sudo: required
services: docker

script: "./travis.sh"
after_failure: "cat cctools.test.fail"

notifications:
  email:
    recipients:
      - cctools-build-list@nd.edu
    on_success: always
    on_failure: always

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    env: "DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos6"
  - os: linux
    compiler: gcc
    env: "DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos7"
  - os: linux
    compiler: gcc
    env: "DOCKER_IMAGE=cclnd/cctools-env:x86_64-ubuntu16.04"
  - os: linux
    compiler: gcc
    env: "DOCKER_IMAGE=cclnd/cctools-env:x86_64-debian9.5"
  - os: linux
    compiler: gcc
    env: "DOCKER_IMAGE=cclnd/cctools-env:x86_64-opensuse42.3"
deploy:
  provider: releases
  file: "/tmp/cctools-*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: cooperative-computing-lab/cctools
    tags: true
  api-key:
    secure: pVs2jvA+y0NYxjhw7zp6+OLssTxOe0lMwqWGWKOeeDihZMmsYeXJ9Z+oxOghfhbcqEv4TnMsYCBkDGLnlSUplWyDPqu/eW0QuvlPzY5VaqqK9aVw1abgKAp77vddub1kHPPqF2axaYIlor6wrMCkyG2ICwmr0mWX+ISNSspsyHzuEA/0XDOMAzY1QjMd08ASScGLAJxHYecRxnjCrUXiN1nMeh266eWsQmWs9PF+DcpKPB9uMohms0Ei7Kj7wnZOMRLRGwM07EYG6ZkDJTxOdjLkOYQ/xhOSTnWynfyaVK8ZLxOKhoCie7oHEuFQRaO8B96o/ddRI2gosMUMU57/Qj5YtPwnBAxIUpUmxe1eRWOGvAWmRuHUxfVR7ICdSsDc9HFKO22tFJCMShLTm528ASnyMVBF2whncSXiba33phFUNKTcJgCcIzvrKazKUzuHyGJrzpjKWYwHR7ufi0v3MrHROD8LGQ2g03YMKmp7/UrMES335Xs5mLCk7uFWh9kSiGvNrFxkk5hWLtzi3Qz81JiyExxjfl8iUVQyL5gggQnotQH7DGeBALmg3LRuXAT/YOEoaTMCh1nEzt16oifnpp+a1yaqwqtq8EHifqu0g3SkmfzhLO/Xz81qVedJ4rauwW0IFzlU81guclAFRDrTHRmmfTeQehZfKhsnO5ElkEo=
