language: c
sudo: required
services: docker
script: ./travis.sh
after_failure: cat cctools.test.fail
matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos6
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-centos7
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-ubuntu16.04
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-debian9.5
  - os: linux
    compiler: gcc
    env: DOCKER_IMAGE=cclnd/cctools-env:x86_64-opensuse42.3
deploy:
  provider: releases
  file: /tmp/cctools-*.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    repo: cooperative-computing-lab/cctools
    tags: true
  api-key:
    secure: vUPY+v2VM8V3834MavH+F2qr/V2er75KdqcxBg/FQ0NVyX+M4fAgycylP0qTm/iUN/ElUp8PXIBrCqUT2aZEo0C+/vwr1bXCoC+P3LlxtnEpUoIoW+b9lmlIXaHovjtto+gjc/zACdnNGfGU8YIijq0w19QvH/ctn/qvCEIjL8fJcJcL7iOGFLG6r1fr5fPZxZgurk7ibkXVI+ywBIvH70ah0HxVB0W8xP3FmDJz6zVmm8I78NjYHxuxSkNgQ8vdsuCOI5YZrQGbgSqlP4j7h5y6fMqOh8HMgRW3niU/dxPJQM9Bo/lGSFQX8FBbdLYYLOgWVaj++2PKwGfgTswMlHAyKgQPe+PlMnRST4g5ukSRQKvNd2bZnScXN/jU95UxnfjdKpa5HoGE/LvG4xUA4wsV4gW4blSMKbbLQU0wtS/Ca2N7Ak8aEwzMF3g0KkOV4LTuvo9ygjmWKN5uUNWAgugy8mrKmYHe8xd/ZuTlILR0N2VU1SD+X2gJPXha5l5QNdaw4Hz1OfOSlYHOfyj9wHBFfeYcHFAIUgerB2Sc0OJ6Vpr00zNUQ6dRcksEIcw+om0RX5rWeobU82q88vTcW29G1WtsTQSEoZBNtJoIh9wwII4jF7W2sv+Cv+sewKZJBQ7nlkVlPYQMnngH3ECIPdzm75gwmnMQHBMAaWWteto=
