on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - 'release/*'
  workflow_dispatch:

name: Test commit

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: ${{ format('cclnd/cctools-env:x86_64-{0}', matrix.os-name) }}
    timeout-minutes: 30
    env:
      GITHUB_DOCKER: yes
    strategy: 
      matrix:
        os-name: ['centos7', 'centos8', 'ubuntu20.04']
    steps:
      - name: checkout CCTools repo
        uses: actions/checkout@v2
      - name: build
        run: ${GITHUB_WORKSPACE}/packaging/scripts/build.sh

  build-osx:
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
      - name: checkout CCTools repo
        uses: actions/checkout@v2
      - name: build
        run: ${GITHUB_WORKSPACE}/packaging/scripts/build.sh

